#!/usr/bin/env bash

SCRIPT_PATH=$(realpath ${BASH_SOURCE[0]:-$0})
SCRIPT_DIR=$(dirname $SCRIPT_PATH)

if [[ ! -f $SCRIPT_DIR/src/Makefile.kernel ]]; then
  echo "$SCRIPT_DIR does not contain a valid Pintos project"
  return 1
fi

export PINTOSPATH=$SCRIPT_DIR
echo "Activating in $PINTOSPATH"

PINTOSUTILS=$PINTOSPATH/src/utils
export PATH=$PATH:$PINTOSUTILS

function format-check {
  echo "Checking formatting for files in $PINTOSPATH"
  clang-format --dry-run $PINTOSPATH/src/**/*.c $PINTOSPATH/src/**/*.h
}

function format {
  echo "Formatting files in $PINTOSPATH"
  clang-format -i $PINTOSPATH/src/**/*.c $PINTOSPATH/src/**/*.h
}

function loop() {
  count=$1
  command=${@:2}
  for i in $(seq $count); do
    echo "[$i/$count] $command"
    eval $command
  done 
}

function stresstest() {
  count=$1
  tmpfile=$(mktemp)
  expected=$2

  for i in $(seq $count); do
      echo "[$i/$count] $command"
      
      rm build/tests/**/*.{output,result} || true
      make check -j10 > $tmpfile 2>&1

      if ! grep -Fq "$expected" "$tmpfile"; then        
          echo "Failed."
          echo "Captured output:"
          cat $tmpfile
          echo "End captured output."
          return 1
      fi
  done
}
